spartamarket/articles/urls.py
from django.urls import path
from . import views



app_name = "articles"
urlpatterns = [
    path('about/', views.about, name='about'),
    path('articles/', views.articles, name='articles'),
    path('articles_view/<int:pk>/', views.articles_view, name='articles_view'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('update/<int:pk>', views.update, name='update'),
    path('like/<int:pk>/', views.like, name='like'),
    path('like/articles/<int:pk>/', views.like_articles, name='like_articles'),
    path('comment_create/<int:pk>/', views.comment_create, name='comment_create'),
    path('comment_delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('hashtag/<int:hash_pk>/', views.hashtag, name='hashtag'),
]

spartamarket/spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from articles import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('articles/', include("articles.urls")),
    path('users/', include("users.urls")),
    path('accounts/', include("accounts.urls")),
    path('stores/', include("stores.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}), # 이부분 추가!!
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spartamarket/stores/urls.py
from django.urls import path
from . import views


app_name = "stores"
urlpatterns = [
    path('stores/', views.stores, name='stores'),
    path('stores_view/<int:pk>/', views.stores_view, name='stores_view'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('update/<int:pk>', views.update, name='update'),
    path('buy/<int:pk>', views.buy, name='buy'),
]

spartamarket/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_id>', views.follow, name='follow'),
    path('gatcha/', views.gatcha, name='gatcha'),
    path('cards/<int:pk>/', views.cards, name='cards'),
    path('card_storage/<int:pk>/', views.card_storage, name='card_storage'),
    path('document/', views.document, name='document'),
]

spartamarket/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Hashtag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to="images/", blank=True)
    views = models.PositiveIntegerField(default=0)
    
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="articles")
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_articles")
    hashtags = models.ManyToManyField(Hashtag, blank=True, related_name="hashtag_articles")
    
    def __str__(self) -> str:
        return self.title
    
    def increase_views(self):
        self.views += 1
        self.save()

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="users")
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return self.content
    

spartamarket/articles/forms.py
from django import forms

from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
        exclude = ("author", "like_users", "hashtags","views",)
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = "__all__"
        exclude = ("article","author",)

spartamarket/articles/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST, require_http_methods
from .forms import ArticleForm, CommentForm
from django.contrib.auth import get_user_model
from django.contrib import messages
from .models import Article, Comment, Hashtag
from accounts.models import User
from stores.models import Store
from django.db.models import Count


def index(request):
    articles = Article.objects.all().order_by("-created_at")[:3]
    stores = Store.objects.all().order_by("-created_at")[:3]
    context = {
        "articles": articles,
        "stores": stores,
    }
    return render(request, 'articles/index.html', context)

# Create your views here.


@require_http_methods(["GET", "POST"])
def articles(request):
    select = request.GET.get("select")
    search = request.GET.get("search")
    sort = request.GET.get("sort", "-created_at")
    if sort == "like_users":
        articles = Article.objects.filter(title__icontains=search).annotate(num_likes=Count('like_users')).order_by('-num_likes', "-created_at")
    else:
        if select == "title":
            articles = Article.objects.filter(
                title__icontains=search).order_by(sort)
        elif select == "content":
            articles = Article.objects.filter(
                content__icontains=search).order_by(sort)
        elif select == "author":
            articles = Article.objects.filter(
                author__username__icontains=search).order_by(sort)
        else:
            articles = Article.objects.all().order_by(sort)
    context = {
        "articles": articles,
        "select": select,
        "search": search,
    }
    return render(request, "articles/articles.html", context)


def like_articles(request, pk):
    sort = request.GET.get("sort", "-created_at")
    member = get_object_or_404(get_user_model(), pk=pk)
    articles = member.like_articles.all().order_by(sort)
    context = {
        "articles": articles,
        "member": member,
    }
    return render(request, "articles/like_articles.html", context)


@require_POST
def like(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)
        else:
            article.like_users.add(request.user)
        return redirect("articles:articles_view", pk)
    return redirect("accounts:login")


def articles_view(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm()
    comments = article.comments.all().order_by("-pk")
    hashtags = article.hashtags.all().order_by("content")
    article.increase_views()
    context = {
        "article": article,
        "comment_form": comment_form,
        "comments": comments,
        "hashtags": hashtags,
    }
    return render(request, "articles/articles_view.html", context)


@require_http_methods(["GET", "POST"])
def create(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = ArticleForm(request.POST, request.FILES)
            if form.is_valid():
                article = form.save(commit=False)
                article.author = request.user
                article.save()
                user = get_object_or_404(User, pk=request.user.pk)
                user.point += 100
                user.save() 
                for word in request.POST.get("hashtag").split():  # content를 공백기준 리스트로 변경
                    if word.startswith('#'):  # '#' 로 시작하는 요소 선택
                        hashtag, created = Hashtag.objects.get_or_create(content=word)
                        article.hashtags.add(hashtag)
                messages.add_message(request, messages.INFO, '게시글이 생성 되었습니다. **100포인트** ')
                return redirect("articles:articles_view", article.pk)
            print(form.errors)
        else:
            form = ArticleForm()
        context = {
            "form": form,
        }
        return render(request, "articles/create.html", context)
    return redirect("accounts:login")


@require_POST
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.author or request.user.is_superuser:
        article.delete()
        messages.add_message(request, messages.INFO, '게시글이 삭제 되었습니다.')
        return redirect("articles:articles")


@require_http_methods(["GET", "POST"])
def update(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        hashtags = article.hashtags.all().order_by("content")
        if request.user == article.author or request.user.is_superuser:
            if request.method == "POST":
                form = ArticleForm(
                    request.POST, request.FILES, instance=article)
                if form.is_valid():
                    article = form.save()
                    article.hashtags.clear()  # 기존에 있던 hashtag 삭제
                    for word in article.content.split():
                        if word.startswith('#'):
                            hashtag, created = Hashtag.objects.get_or_create(content=word)
                            article.hashtags.add(hashtag)
                messages.add_message(request, messages.INFO, '게시글이 수정 되었습니다.')
                return redirect("articles:articles_view", article.pk)
            context = {
                "article": article,
                "hashtags": hashtags,
            }
            return render(request, "articles/update.html", context)
        else:
            return redirect("articels:articles")
    return redirect("accounts:login")


@require_POST
def comment_create(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.author = request.user
            comment.save()
            user = get_object_or_404(User, pk=request.user.pk)
            user.point += 10
            user.save()
            messages.add_message(request, messages.INFO, ' **10포인트** ')
            return redirect("articles:articles_view", pk=pk)
    return redirect("accounts:login")


@require_POST
def comment_delete(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.user == comment.author or request.user.is_superuser:
        comment.delete()
        return redirect("articles:articles_view", pk)
    else:
        return redirect("articles:articles_view", pk)


def hashtag(request, hash_pk):
    hashtag = get_object_or_404(Hashtag, pk=hash_pk)
    articles = hashtag.hashtag_articles.order_by('-pk')
    
    context = {
        'hashtag': hashtag, 
        'articles': articles,
    }
    return render(request, 'articles/hashtag.html', context)

def about(request):
    return render(request, 'articles/about.html')

spartamarket/articles/templates/articles/articles_view.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <style>
    .title_box {
      margin: 20px;
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
    .sort_box {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
    .btn_set{
      background-color: transparent;
      border-radius: 5px;
      height: 50px;
      margin-right: 50px;
    }
  </style>
{% endblock %}


{% block content %}
<div class="title_box">
  <h1> {{ article.title }} </h1> 
  <form action="{% url "users:profile" article.author.username %}" method="GET">
    <button class="btn_set" type="submit">작성자 프로필 보기</button>
  </form>
  <form action="{% url 'articles:like' article.pk %}" method="POST">
    {% csrf_token %}
    {% if request.user in article.like_users.all %}
    {% comment %} 좋아요 상태 {% endcomment %}
    <button class="btn_set" >좋아요 <img src="{% static "articles/heart.png" %}" style="width: 30px; height: 30px;"></button> 
    {% else %}
    {% comment %} 안좋아요 상태 {% endcomment %}
    <button class="btn_set" >안좋아요 <img src="{% static "articles/love.png" %}" style="width: 30px; height: 30px;"></button>
    {% endif %}
  </form>
    <a href="{% url 'articles:create' %}"><button class="btn_set">새로운 글 작성</button></a>
    <a href="{% url 'articles:articles' %}"><button class="btn_set">목록 보기</button></a><br />
</div>
<hr /><br />

<div style="display: flex; flex-direction: column; align-items: center;">
  <div style="display: flex; margin-top: 5px;">
  <h3 style="margin-right: 100px;">[ {{ article.author }} ] 님의 게시물</h3>
  <label style="margin-right: 30px;"> <strong> 조희수 {{ article.views }} 회 </strong> </label>
    {% if article.author == request.user or request.user.is_superuser or is_staff%}
      <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" style="margin-right: 5px;">삭제하기</button>
      </form>
      <form action="{% url 'articles:update' article.pk %}" method="GET">
        <button type="submit">수정하기</button>
      </form>
    {% endif %}
  </div>
  {% if article.image %}
    <img class="imgs" src="{{ article.image.url }}" alt="{{ article.image }}" /><br />
  {% endif %}
  <br>
  <p>작성자 : {{ article.author }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>생성일자 : {{ article.created_at }}</p>
  <div>
  {% for hashtag in hashtags %}
  <a href="{% url "articles:hashtag" hashtag.pk %}" style="margin: 10px;"> {{ hashtag.content }} </a>
  {% endfor %}
</div>
  <br><br>
</div>
  <br />
  <hr />
  {% if request.user.is_authenticated %}
    <h3>댓글 적기</h3>
    <form action="{% url 'articles:comment_create' article.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <input type="submit" value="작성" />
    </form>
  {% endif %}
  <br>
  {% if comments %}
  <h3>댓글</h3><hr>
  {% for comment in comments %}
  <ul>
    <p>작성자 : {{ comment.author }}</p>
    <p>내용 : {{ comment.content }}</p>
    <p>작성일 : {{ comment.created_at }}</p>
    {% if comment.author == request.user or request.user.is_superuser or is_staff %}
    <form action="{% url 'articles:comment_delete' comment.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제" />
    </form>
    {% endif %}
  </ul>
  <hr />
  {% endfor %}
  {% endif %}
    <br>
{% endblock %}

spartamarket/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <style>
    .lable_size {
      width: 200px;
      text-align: center;
    }
    .table{
      display: flex;
      flex-direction: row;
      align-items: center;
      margin-top: 20px;
    }
    .div_box{
      display: flex;
      flex-direction: column;
    }
  </style>
{% endblock %}

{% block content %}
  <div>
    <br />
    <h2>게시글</h2> <hr />
  </div>

  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="table">
      <div>
        <label class="lable_size" for="id_image">게시글이미지:</label>
      </div>
      <div class="div_box">
        <img id="preview" style="width: 300px; height: 300px;" src="{% static 'articles/image-gallery.png' %}" />
        <input type="file" name="image" accept="image/*" id="id_image" onchange="readURL(this);" />
      </div>
    </div>
    <div class="table">
        <label class="lable_size" for="id_title">제목:</label>
        <input type="text" name="title" maxlength="50" required id="id_title" />
    </div>
    <div class="table">
        <label class="lable_size" for="hashtag">해시태그:</label>
        <input type="text" name="hashtag" style="margin-right: 20px;"/>
        앞에 "#" 을 붙여서 작성해주세요
    </div>
    <div class="table">
        <label class="lable_size" for="id_content">내용:</label>
        <textarea name="content" cols="40" rows="10" required id="id_content"></textarea>
    </div>
    <div style="display: flex; justify-content: right; margin: 50px 0 ;">
      <button type="submit" style="margin-right: 100px;">등록하기</button>
    </div>
  </form>
  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader()
        reader.onload = function (e) {
          document.getElementById('preview').src = e.target.result
        }
        reader.readAsDataURL(input.files[0])
      } else {
        document.getElementById('preview').src = ''
      }
    }
  </script>
{% endblock %}

spartamarket/articles/templates/articles/hashtag.html
<!-- hashtag.html -->

{% extends 'base.html' %}

{% block content %}
  <div>
    <h2>{{ hashtag.content }}관련 게시글</h2>
    <p>{{ articles|length }}개의 게시글</p>
  </div>
  
  <hr>

  <div class="row row-cols-1 row-cols-md-3 g-4" id="articleContainer">
    {% for article in articles %}
      <a href="{% url 'articles:articles_view'  article.pk  %}" style="width: 326px;">
        <div class="col">
          <div class="card" style="align-items: center;">
            <img class="imgs" src="{{ article.image.url }}" class="card-img-top" />
            <div class="card-body">
              <h3 class="card-title">{{ article.title }}</h3>
              <div style="display: flex; flex-direction: row; margin-top: 10px;">
                <p class="card-text" style="margin-right: 20px;">{{ article.like_users.all|length }} 좋아요</p>
                <p class="card-text" style="margin-right: 20px;">{{ article.views }} 조회수 </p>
                  <p class="card-text">{{ article.comments.all|length }} 댓글</p>
              </div>
            </div>
          </div>
        </div>
      </a>
    {% endfor %}
  </div>
{% endblock %}

spartamarket/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  <style>
    .main_img {
      padding-top: 30px;
      padding-bottom: 30px;
      display: flex;
      justify-content: center;
      background-color: var(--standard_color);
    }
    header {
      background-color: transparent;
      padding: 50px 0;
      overflow: auto;
      box-sizing: border-box;
    }
    
    h1 {
      height: 100px;
    }
    
    h1 span {
      position: relative;
      top: 20px;
      display: inline-block;
      animation: bounce 0.6s ease infinite alternate;
      font-family: 'Titan One', cursive;
      font-size: 80px;
      color: var(--background_color);
      text-shadow: 0 1px 0 var(--background_color), 0 2px 0 #ccc, 0 3px 0 #ccc, 0 4px 0 #ccc, 0 5px 0 #ccc, 0 6px 0 transparent, 0 7px 0 transparent, 0 8px 0 transparent, 0 9px 0 transparent, 0 10px 10px rgba(0, 0, 0, 0.4);
    }
    
    h1 span:nth-child(2) {
      animation-delay: 0.1s;
    }
    
    h1 span:nth-child(3) {
      animation-delay: 0.2s;
    }
    
    h1 span:nth-child(4) {
      animation-delay: 0.3s;
    }
    
    h1 span:nth-child(5) {
      animation-delay: 0.4s;
    }
    
    h1 span:nth-child(6) {
      animation-delay: 0.5s;
    }
    
    h1 span:nth-child(7) {
      animation-delay: 0.6s;
    }
    
    h1 span:nth-child(8) {
      animation-delay: 0.7s;
    }
    
    h1 span:nth-child(9) {
      animation-delay: 0.8s;
    }
    
    @keyframes bounce {
      100% {
        top: -20px;
        text-shadow: 0 1px 0 #ffffff, 0 2px 0 #ccc, 0 3px 0 #ccc, 0 4px 0 #ccc, 0 5px 0 #ccc, 0 6px 0 #ccc, 0 7px 0 #ccc, 0 8px 0 #ccc, 0 9px 0 #ccc, 0 50px 25px rgba(0, 0, 0, 0.2);
      }
    }
  </style>
{% endblock %}

{% block main %}
  <div class="main_img">
    <header style="margin: 0 100px;">
      <h1>
        <span>S</span>
        <span>p</span>
        <span>a</span>
        <span>r</span>
        <span>t</span>
        <span>a</span>
      </h1>
      <h1>
        <span>M</span>
        <span>a</span>
        <span>r</span>
        <span>k</span>
        <span>e</span>
        <span>t</span>
      </h1>
    </header>
  </div>
  {% endblock %}
  
  {% block content %}
<br>
  <h2 style="text-align: center; margin-top: 10px;">최근 작성된 게시물</h2><hr>
<br>
  <div style="display: flex; justify-content: center;">
    <div class="row row-cols-1 row-cols-md-3 g-4" id="articleContainer">
      {% for article in articles %}
        <a href="{% url 'articles:articles_view'  article.pk  %}" style="width: 326px;">
          <div class="col">
            <div class="card" style="align-items: center;">
              <img class="imgs" src="{% if article.image %}{{ article.image.url }}{% else %} {% static 'articles/image-gallery.png' %} {% endif %}" class="card-img-top" />
              <div class="card-body">
                <h3 class="card-title">{{ article.title }}</h3>
                <div style="display: flex; flex-direction: row; margin-top: 10px;">
                  <p class="card-text" style="margin-right: 20px;">{{ article.like_users.all|length }} 좋아요</p>
                  <p class="card-text" style="margin-right: 20px;">{{ article.views }} 조회수 </p>
                  <p class="card-text">{{ article.comments.all|length }} 댓글</p>
                </div>
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
<br>
  <h2 style="text-align: center; margin-top: 10px;">최근 작성된 상점</h2><hr>
  <br>
  <div style="display: flex; justify-content: center;">
    <div class="row row-cols-1 row-cols-md-3 g-4" id="storeContainer">
      {% for store in stores %}
        <a href="{% url 'stores:stores_view' store.pk %}" style="width: 326px;">
          <div class="col">
            <div class="card" style="align-items: center;">
              <img style="width: 200px; margin: 20px;" src="{% static 'stores/pokemon ('|add:store.card.cardnum|add:').png' %}" class="card-img-top" />
              <div class="card-body">
                <h3 class="card-title">{{ store.title }}</h3>
                <div style="display: flex; flex-direction: row; margin-top: 10px;">
                  <label class="card-title">{{ store.price }} 포인트</label>
                </div>
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
  <br>
{% endblock %}

spartamarket/articles/templates/articles/like_articles.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <style>
    .title_box {
      margin: 20px;
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
    .sort_box {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
  </style>
{% endblock %}

{% block content %}
  <div class="title_box">
    <h1>{{ member.username }}님의 찜 게시판</h1>
    <form action="{% url 'articles:like_articles' member.id %}" method="GET">
      <div class="sort_box">
        <select class="form-select" aria-label="Default select example" name="sort" style="width: 200px; margin-right: 20px;">
          <option selected value="title">제목 순</option>
          <option value="content">내용 순</option>
          <option value="created_at">생성일 순</option>
          <option value="-created_at">최신 순</option>
        </select>
        <button type="submit">정렬</button>
      </div>
    </form>
  </div>
  <hr /><br />

  <div style="display: flex; justify-content: center;">
    <div class="row row-cols-1 row-cols-md-3 g-4" id="articleContainer">
      {% for article in articles %}
        <a href="{% url 'articles:articles_view'  article.pk  %}" style="width: 326px;">
          <div class="col">
            <div class="card" style="align-items: center;">
              <img class="imgs" src="{{ article.image.url }}" class="card-img-top" />
              <div class="card-body">
                <h3 class="card-title">{{ article.title }}</h3>
                <div style="display: flex; flex-direction: row;">
                  <div style="display: flex; flex-direction: row; margin-top: 10px;">
                    <p class="card-text" style="margin-right: 20px;">{{ article.like_users.all|length }} 좋아요</p>
                    <p class="card-text" style="margin-right: 20px;">{{ article.views }} 조회수 </p>
                  <p class="card-text">{{ article.comments.all|length }} 댓글</p>
                  </div>
              </div> 
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
  <br />
{% endblock %}

spartamarket/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <style>
    .lable_size {
      width: 200px;
      text-align: center;
    }
    .table{
      display: flex;
      flex-direction: row;
      align-items: center;
      margin-top: 20px;
    }
    .div_box{
      display: flex;
      flex-direction: column;
    }
  </style>
{% endblock %}

{% block content %}
  <div>
    <br />
    <h2>게시글 수정</h2> <hr />
  </div>

  <form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="table">
      <div>
        <label class="lable_size" for="id_image">게시글이미지:</label>
      </div>
      <div class="div_box">
        <img id="preview" style="width: 300px; height: 300px;" src="{% if article.image %} {{ article.image.url }} {% else %} {% static 'article/image-gallery.png' %} {% endif %} " />
        <input type="file" name="image" accept="image/*" id="id_image" onchange="readURL(this);" />
      </div>
    </div>
    <div class="table">
        <label class="lable_size" for="id_title">제목:</label>
        <input type="text" name="title" maxlength="50" required id="id_title" value="{{ article.title }}" />
    </div>
    <div class="table">
      <label class="lable_size" for="hashtag">해시태그:</label>
      <input type="text" name="hashtag" required id="hashtag" value="{% for hashtag in hashtags %} {{ hashtag }} {% endfor %}" style="margin-right: 20px;"/>앞에 "#" 을 붙여서 작성해주세요
  </div>
    <div class="table">
        <label class="lable_size" for="id_content">내용:</label>
        <textarea name="content" cols="40" rows="10" required id="id_content">{{ article.content }}</textarea>
    </div>
    <div style="display: flex; justify-content: right; margin: 50px 0 ;">
      <button type="submit" style="margin-right: 100px;">수정하기</button>
    </div>
  </form>
  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader()
        reader.onload = function (e) {
          document.getElementById('preview').src = e.target.result
        }
        reader.readAsDataURL(input.files[0])
      } else {
        document.getElementById('preview').src = ''
      }
    }
  </script>
{% endblock %}