spartamarket/spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from articles import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('articles/', include("articles.urls")),
    path('users/', include("users.urls")),
    path('accounts/', include("accounts.urls")),
    path('stores/', include("stores.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}), # 이부분 추가!!
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spartamarket/stores/urls.py
from django.urls import path
from . import views


app_name = "stores"
urlpatterns = [
    path('stores/', views.stores, name='stores'),
    path('stores_view/<int:pk>/', views.stores_view, name='stores_view'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('update/<int:pk>', views.update, name='update'),
    path('buy/<int:pk>', views.buy, name='buy'),
]

spartamarket/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_id>', views.follow, name='follow'),
    path('gatcha/', views.gatcha, name='gatcha'),
    path('cards/<int:pk>/', views.cards, name='cards'),
    path('card_storage/<int:pk>/', views.card_storage, name='card_storage'),
    path('document/', views.document, name='document'),
]

spartamarket/stores/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Store(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to="images/", blank=True)
    price = models.IntegerField()
    card = models.ForeignKey(settings.AUTH_CARD_MODEL, on_delete=models.CASCADE, related_name="cards")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="stores")
    
    def __str__(self) -> str:
        return self.title

spartamarket/stores/forms.py
from django import forms

from .models import Store

class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = "__all__"
        exclude = ("author",)
        

spartamarket/stores/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST, require_http_methods
from .forms import StoreForm
from django.contrib.auth import get_user_model
from accounts.models import User
from .models import Store
from django.contrib import messages

# Create your views here.


@require_http_methods(["GET", "POST"])
def stores(request):
    select = request.GET.get("select")
    search = request.GET.get("search")
    sort = request.GET.get("sort", "-created_at")
    if select == "title":
        stores = Store.objects.filter(
            title__icontains=search).order_by(sort)
    elif select == "content":
        stores = Store.objects.filter(
            content__icontains=search).order_by(sort)
    elif select == "author":
        stores = Store.objects.filter(
            author__username__icontains=search).order_by(sort)
    else:
        stores = Store.objects.all().order_by(sort)
        
    context = {
        "stores": stores,
        "select": select,
        "search": search,
    }
    return render(request, "stores/stores.html", context)


def like_stores(request, pk):
    sort = request.GET.get("sort", "-created_at")
    member = get_object_or_404(get_user_model(), pk=pk)
    stores = member.like_stores.all().order_by(sort)
    context = {
        "stores": stores,
        "member": member,
    }
    return render(request, "stores/like_stores.html", context)


@require_POST
def like(request, pk):
    if request.user.is_authenticated:
        store = get_object_or_404(Store, pk=pk)
        if store.like_users.filter(pk=request.user.pk).exists():
            store.like_users.remove(request.user)
        else:
            store.like_users.add(request.user)
        return redirect("stores:stores_view", pk)
    return redirect("accounts:login")


def stores_view(request, pk):
    store = get_object_or_404(Store, pk=pk)
    context = {
        "store": store,
    }
    return render(request, "stores/stores_view.html", context)


@require_http_methods(["GET", "POST"])
def create(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = StoreForm(request.POST)
            if form.is_valid():
                store = form.save(commit=False)
                store.author = request.user
                store.save()
                seller = get_object_or_404(User, pk=store.author.pk)
                card = store.card
                seller.cards.remove(card)
                messages.add_message(request, messages.INFO, '상점이 등록되었습니다.')
                return redirect("stores:stores_view", store.pk)
        else:
            form = StoreForm()
        context = {
            "form": form,
        }
        return render(request, "stores/create.html", context)
    return redirect("accounts:login")


@require_POST
def delete(request, pk):
    if request.user.is_authenticated:
        store = get_object_or_404(Store, pk=pk)
        if request.user == store.author or request.user.is_superuser:
            seller = get_object_or_404(User, pk=store.author.pk)
            card = store.card
            seller.cards.add(card)
            store.delete()
            messages.add_message(request, messages.INFO, '상점이 삭제 되었습니다.')
            return redirect("stores:stores")
    return redirect("accounts:login")

@require_POST
def buy(request, pk):
    if request.user.is_authenticated:
        store = get_object_or_404(Store, pk=pk)
        if request.user != store.author:
            seller = get_object_or_404(User, pk=store.author.pk)
            buyer = get_object_or_404(User, pk=request.user.pk)
            if buyer.point >= store.price:
                buyer.point -= store.price
                seller.point += store.price
                buyer.save()
                seller.save()
                card = store.card
                buyer.cards.add(card)
                store.delete()
                return redirect("stores:stores")
            else:
                messages.add_message(request, messages.INFO, '포인드가 부족합니다.')
                return redirect("stores:stores_view", pk)
    return redirect("accounts:login")


@require_http_methods(["GET", "POST"])
def update(request, pk):
    if request.user.is_authenticated:
        store = get_object_or_404(Store, pk=pk)
        if request.user == store.author or request.user.is_superuser:
            if request.method == "POST":
                form = StoreForm(request.POST, instance=store)
                if form.is_valid():
                    store = form.save()
                    messages.add_message(request, messages.INFO, '상점이 수정 되었습니다.')
                return redirect("stores:stores_view", store.pk)
            context = {
                "store": store,
            }
            return render(request, "stores/update.html", context)
        else:
            return redirect("stores:stores")
    return redirect("accounts:login")

spartamarket/stores/templates/stores/create.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style>
  .lable_size {
    width: 200px;
    text-align: center;
  }

  .table {
    display: flex;
    flex-direction: row;
    align-items: center;
    margin-top: 20px;
  }

  .div_box {
    display: flex;
    flex-direction: column;
  }
</style>
{% endblock %}

{% block content %}
<div>
  <br />
  <h2>상품정보</h2>
  <hr />
</div>

<form action="{% url 'stores:create' %} " method="POST">
  {% csrf_token %}
  <div class="table">
    <div>
      <label class="lable_size" for="id_image">상품이미지:</label>
    </div>
    <div class="div_box">
      <input type="hidden" name="card" value="{{ card_choice.pk }}">
      <img id="preview" style="width: 200px; "
        src="{% if card_choice %}{% static 'stores/pokemon ('|add:card_choice.cardnum|add:').png' %}{% else %}{% static 'stores/pokemon(select).jpg' %}{% endif %}" />
      <br />
      <button onclick="window.location.href='{% url 'users:card_storage' request.user.pk %}'">카드 선택하기</button>
    </div>
  </div>
  <div class="table">
    <label class="lable_size" for="id_title">상품명:</label>
    <input type="text" name="title" maxlength="50" required id="id_title" />
  </div>
  <div class="table">
    <label class="lable_size" for="price">판매가격:</label>
    <input type="number" name="price" required id="price" style="margin-right: 20px;" /> 포인트
  </div>
  <div class="table">
    <label class="lable_size" for="id_content">상품설명:</label>
    <textarea name="content" cols="40" rows="10" required id="id_content"></textarea>
  </div>
  <div style="display: flex; justify-content: right; margin: 50px 0 ;">
    <button type="submit" style="margin-right: 100px;">판매하기</button>
  </div>
</form>
<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader()
      reader.onload = function (e) {
        document.getElementById('preview').src = e.target.result
      }
      reader.readAsDataURL(input.files[0])
    } else {
      document.getElementById('preview').src = ''
    }
  }
</script>
{% endblock %}

spartamarket/stores/templates/stores/stores.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <style>
    .title_box {
      margin: 20px;
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
    .sort_box {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
  </style>
{% endblock %}

{% block content %}
  <div class="title_box">
    <h1>판매 게시판</h1>
    <form action="{% url 'stores:stores' %}" method="GET">
      <div class="sort_box">
        <input type="hidden" name="select" value="{{ request.GET.select }}" />
        <input type="hidden" name="search" value="{{ request.GET.search }}" />
        <select class="form-select" aria-label="Default select example" name="sort" style="width: 200px; margin-right: 20px;">
          <option selected value="title">제목 순</option>
          <option value="content">내용 순</option>
          <option value="created_at">생성일 순</option>
          <option value="-created_at">최신 순</option>
          <option value="-price">높은 가격순</option>
          <option value="price">낮은 가격순</option>
        </select>
        <button type="submit">정렬</button>
      </div>
    </form>
  </div>
  <hr /><br />
  <div style="display: flex; justify-content: center;">
    <div class="row row-cols-1 row-cols-md-3 g-4" id="storeContainer">
      {% for store in stores %}
        <a href="{% url 'stores:stores_view' store.pk %}" style="width: 326px;">
          <div class="col">
            <div class="card" style="align-items: center;">
              <img style="width: 200px; margin: 20px;" src="{% static 'stores/pokemon ('|add:store.card.cardnum|add:').png' %}" class="card-img-top" />
              <div class="card-body">
                <h3 class="card-title">{{ store.title }}</h3>
                <div style="display: flex; flex-direction: row; margin-top: 10px;">
                  <label class="card-title">{{ store.price }} 포인트</label>
                </div>
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
  <br />
{% endblock %}

spartamarket/stores/templates/stores/stores_view.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <style>
    .title_box {
      margin: 20px;
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
    .sort_box {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
    .btn_set {
      background-color: transparent;
      border-radius: 5px;
      height: 50px;
      margin-right: 50px;
    }

    .container {
      width: 220px; height: 310px; transition : all 0.1s;
      position: relative;
    }
    .overlay {
      position: absolute;
      width: 220px;
      height: 310px;
      background: linear-gradient(105deg,
      transparent 40%,
      rgba(255, 219, 112, 0.8) 45%,
      rgba(132, 50, 255 ,0.6) 50%,
      transparent 54%);
      filter: brightness(1.1) opacity(0.8);
      mix-blend-mode: color-dodge;
      background-size: 150% 150%;
      background-position: 100%;
      transition: all 0.1s;
      z-index: 1;
    }
    .card {
      width: 220px; height: 310px;
      background-size: cover;
    }
  </style>
{% endblock %}

{% block content %}

  <div class="title_box">
    <h1>{{ store.title }}</h1> 
    <form action="{% url 'users:profile' store.author.username  %}" method="GET">
      <button class="btn_set" type="submit">작성자 프로필 보기</button>
    </form>
    <a href="{% url 'stores:create' %}"><button class="btn_set">새로운 글 작성</button></a>
    <a href="{% url 'stores:stores' %}"><button class="btn_set">목록 보기</button></a><br />
  </div>
  <hr />
<div style="display: flex; flex-direction: column; align-items: center;">
  <div style="display: flex; margin-top: 5px;">
    <h3 style="margin-right: 100px;">[ {{ store.author }} ] 님의 게시물</h3>
    {% if store.author == request.user or request.user.is_superuser or is_staff %}
      <form action="{% url 'stores:delete' store.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" style="margin-right: 5px;">삭제하기</button>
      </form>
      <form action="{% url 'stores:update' store.pk %}" method="GET">
        <button type="submit">수정하기</button>
      </form>
    {% endif %}
  </div>
   <br />
   <div class="container">
    <div class="overlay"></div>
    <img class="card" src="{% static 'stores/pokemon ('|add:store.card.cardnum|add:').png' %}"/><br />
  </div>
    <br />
  <p>내용 : {{ store.content }}</p>
  <p>생성일자 : {{ store.created_at }}</p>
  <p>판매가격 : {{ store.price }} 포인트</p>

  {% if store.author != request.user %}
  <br>
  <form action="{% url 'stores:buy' store.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit" style="margin-right: 5px;">구매하기</button>
  </form>
  <br>
  {% endif %}
</div>

<script>
  var container = document.querySelector('.container')
  var overlay = document.querySelector('.overlay')
  container.addEventListener('mousemove', function(e){
    var x = e.offsetX
    var y = e.offsetY
    var rotateY = -1/5 * x + 20
    var rotateX = 4/30 * y - 20

    overlay.style = `background-position : ${x/5 + y/5}%; filter : opacity(${x/200}) brightness(1.2)`

    container.style = `transform : perspective(350px) rotateX(${rotateX}deg) rotateY(${rotateY}deg)`
  })

  container.addEventListener('mouseout', function(){
    overlay.style = 'filter : opacity(0)'
    container.style = 'transform : perspective(350px) rotateY(0deg) rotateX(0deg)'
  })
</script>
{% endblock %}

spartamarket/stores/templates/stores/update.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <style>
    .lable_size {
      width: 200px;
      text-align: center;
    }
    .table {
      display: flex;
      flex-direction: row;
      align-items: center;
      margin-top: 20px;
    }
    .div_box {
      display: flex;
      flex-direction: column;
    }
  </style>
{% endblock %}

{% block content %}
  <div>
    <br />
    <h2>상품정보</h2> <hr />
  </div>

  <form action="{% url 'stores:update' store.pk %}" method="POST">
    {% csrf_token %}
    <div class="table">
      <div>
        <label class="lable_size" for="id_image">상품이미지:</label>
      </div>
      <div class="div_box">
        <input type="hidden" name="card" value="{{ card_choice }}">
        <img id="preview" style="width: 200px; margin: 20px;" src="{% static 'stores/pokemon ('|add:store.card.cardnum|add:').png' %}" />
      </div>
    </div>
    <div class="table">
      <label class="lable_size" for="id_title">상품명:</label>
      <input type="text" name="title" maxlength="50" required id="id_title" value="{{ store.title }}" />
    </div>
    <div class="table">
      <label class="lable_size" for="id_price">가격:</label>
      <input type="number" name="price" required id="id_price" value="{{ store.price }}" style="margin-right: 20px;" />포인트
    </div>
    <div class="table">
      <label class="lable_size" for="id_content">상품설명:</label>
      <textarea name="content" cols="40" rows="10" required id="id_content">{{ store.content }}</textarea>
    </div>
    <div style="display: flex; justify-content: right; margin: 50px 0 ;">
      <button type="submit" style="margin-right: 100px;">수정하기</button>
    </div>
  </form>
  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader()
        reader.onload = function (e) {
          document.getElementById('preview').src = e.target.result
        }
        reader.readAsDataURL(input.files[0])
      } else {
        document.getElementById('preview').src = ''
      }
    }
  </script>
{% endblock %}