spartamarket/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

spartamarket/articles/urls.py
from django.urls import path
from . import views



app_name = "articles"
urlpatterns = [
    path('about/', views.about, name='about'),
    path('articles/', views.articles, name='articles'),
    path('articles_view/<int:pk>/', views.articles_view, name='articles_view'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('update/<int:pk>', views.update, name='update'),
    path('like/<int:pk>/', views.like, name='like'),
    path('like/articles/<int:pk>/', views.like_articles, name='like_articles'),
    path('comment_create/<int:pk>/', views.comment_create, name='comment_create'),
    path('comment_delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('hashtag/<int:hash_pk>/', views.hashtag, name='hashtag'),
]

spartamarket/spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from articles import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('articles/', include("articles.urls")),
    path('users/', include("users.urls")),
    path('accounts/', include("accounts.urls")),
    path('stores/', include("stores.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}), # 이부분 추가!!
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spartamarket/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_id>', views.follow, name='follow'),
    path('gatcha/', views.gatcha, name='gatcha'),
    path('cards/<int:pk>/', views.cards, name='cards'),
    path('card_storage/<int:pk>/', views.card_storage, name='card_storage'),
    path('document/', views.document, name='document'),
]

spartamarket/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Card(models.Model):
    cardnum = models.TextField()

    def __str__(self):
        return self.cardnum
    
class User(AbstractUser):
    point = models.IntegerField(default=0)
    image = models.ImageField(upload_to="images/", blank=True)
    following = models.ManyToManyField('self',symmetrical=False, related_name="followers")
    cards = models.ManyToManyField(Card, blank=True, related_name="card_users")

spartamarket/stores/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Store(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to="images/", blank=True)
    price = models.IntegerField()
    card = models.ForeignKey(settings.AUTH_CARD_MODEL, on_delete=models.CASCADE, related_name="cards")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="stores")
    
    def __str__(self) -> str:
        return self.title

spartamarket/users/models.py
from django.db import models

# Create your models here.

spartamarket/users/views.py
import random
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST, require_http_methods
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from articles.models import Article
from accounts.models import User, Card
from django.contrib import messages
# Create your views here.


@require_http_methods(["GET", "POST"])
def profile(request, username):
    user = get_object_or_404(User, username=username)
    member = get_object_or_404(get_user_model(), username=username)
    articles = Article.objects.filter(author=user).order_by("-created_at")
    context = {
        "user": user,
        "articles": articles,
        "member": member,
    }
    return render(request, "users/profile.html", context)


@require_POST
def follow(request, user_id):
    if request.user.is_authenticated:
        member = get_object_or_404(get_user_model(), pk=user_id)
        if request.user != member:
            if member.followers.filter(pk=request.user.pk).exists():
                member.followers.remove(request.user)
            else:
                member.followers.add(request.user)
        return redirect("users:profile", member.username)
    return redirect("accounts:login")


def gatcha(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            user = request.user
            if user.point >= 100:
                user.point -= 100
                user.save()
                gatcha = random.randint(1, 50)
                card = Card.objects.create(cardnum=gatcha)
                user.cards.add(card)
                context = {
                    "gatcha": str(gatcha),
                }
                return render(request, "users/gatcha.html", context)
            messages.add_message(request, messages.INFO, '포인트가 부족합니다.')
            return render(request, "users/gatcha.html")
        return render(request, "users/gatcha.html")
    return redirect("accounts:login")


def cards(request, pk):
    user = get_object_or_404(User, pk=pk)
    all_cards = user.cards.all().order_by("cardnum")
    # 중복을 제거할 빈 리스트를 생성
    unique_cards = []
    # 이미 추가한 카드의 번호를 추적하기 위한 집합을 생성
    added_card_nums = set()
    # 중복을 제거하고 유니크한 카드만 추가
    for card in all_cards:
        if card.cardnum not in added_card_nums:
            unique_cards.append(card)
            added_card_nums.add(card.cardnum)
    card_list = []
    card_nums = sorted(list(added_card_nums))
    for i in range(1, 51):
        if str(i) in card_nums:
            card_list.append(unique_cards[card_nums.index(str(i))])
        else:
            card_list.append("blank")
    count = len(unique_cards)
    context = {
        "user": user,
        "cards": unique_cards,
        "count": count,
        "card_list": card_list,
    }
    return render(request, "users/cards.html", context)


def card_storage(request, pk):
    if request.user.is_authenticated:
        user = get_object_or_404(User, pk=pk)
        if request.method == "POST":
            cardnum = request.POST.get("cardnum")
            card_choices = Card.objects.filter(cardnum=cardnum, card_users=request.user)
            if card_choices.exists():
                context = {
                    "card_choice": card_choices.first(),  
                }
            return render(request, "stores/create.html", context)
        all_cards = user.cards.all().order_by("cardnum")
        count = len(all_cards)
        context = {
            "user": user,
            "all_cards": all_cards,
            "count": count,
        }
        return render(request, "users/card_storage.html", context)
    return redirect("accounts:login")


def document(request):
    cards = [str(i) for i in range(1, 51)]
    context = {
        "cards": cards,
    }
    return render(request, "users/document.html", context)

spartamarket/users/templates/users/card_storage.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<br>
<div class="title_box">
    <h1>{{ user.username }}님의 보유한 카드 {{ user.cards.count }} 개</h1> 
  </div>
  <br><hr>
<br>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
  {% for card in all_cards %}
  <form action="{% url 'users:card_storage' request.user.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit" name="cardnum" value="{{ card.cardnum }}" style="display: flex; flex-direction: column; align-items: center; width: 220px; border: none; background: none; padding: 0;">
      <label style="text-align: center;"> No. {{ card.cardnum }}</label>
      <img src="{% static 'stores/pokemon ('|add:card.cardnum|add:').png' %}" style="width: 200px; margin: 10px;">
    </button>
  </form>
  
  {% endfor %}
</div>


{% endblock content %}

spartamarket/users/templates/users/cards.html
{% extends "base.html" %}
{% load static %}

{% block style %}
  <style>
    .title_box {
      margin: 20px;
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
    .sort_box {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
    .btn_set {
      background-color: transparent;
      border-radius: 5px;
      height: 50px;
      margin-right: 50px;
    }

    .container {
      width: 220px; height: 310px; transition : all 0.1s;
      position: relative;
    }
    .overlay {
      position: absolute;
      width: 220px;
      height: 310px;
      background: linear-gradient(105deg,
      transparent 40%,
      rgba(255, 219, 112, 0.8) 45%,
      rgba(132, 50, 255 ,0.6) 50%,
      transparent 54%);
      filter: brightness(1.1) opacity(0.8);
      mix-blend-mode: color-dodge;
      background-size: 150% 150%;
      background-position: 100%;
      transition: all 0.1s;
      z-index: 1;
    }
    .card {
      width: 220px; height: 310px;
      background-size: cover;
    }
  </style>
{% endblock %}

{% block content %}
<br>
<div class="title_box">
    <h1>{{ user.username }}님의 보유한 카드 {{ user.cards.count }} 개 | 도감 완성률 {{count}} / 50</h1> 
  </div>
  <br><hr>
<br>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
  {% for card in card_list %}
  {% if card != "blank" %}
  <div style="display: flex; flex-direction: column; justify-content: center; margin: 10px;">
    <div style="text-align: center;"> No. {{ card.cardnum }}</div>
    <div class="container" id="container_{{ card }}"> <!-- 각 container에 고유한 id 추가 -->
      <div class="overlay"></div>
      <img class="card" src="{% static 'stores/pokemon ('|add:card.cardnum|add:').png' %}" >
    </div>
  </div>
  {% else %}
  <div style="display: flex; flex-direction: column; justify-content: center; margin: 10px;">
    <div style="text-align: center;"> No. ???</div>
    <div class="container" id="container_{{ card }}"> <!-- 각 container에 고유한 id 추가 -->
      <img class="card" src="{% static 'stores/pokemon (blank).png' %}" >
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>

<script>
  // 각 container에 대해 이벤트 리스너 추가
  {% for card in cards %}
  var container_{{ card }} = document.querySelector('#container_{{ card }}');
  var overlay_{{ card }} = container_{{ card }}.querySelector('.overlay');

  container_{{ card }}.addEventListener('mousemove', function(e){
    var x = e.offsetX
    var y = e.offsetY
    var rotateY = -1/5 * x + 20
    var rotateX = 4/30 * y - 20

    overlay_{{ card }}.style = `background-position : ${x/5 + y/5}%; filter : opacity(${x/200}) brightness(1.2)`

    container_{{ card }}.style = `transform : perspective(350px) rotateX(${rotateX}deg) rotateY(${rotateY}deg)`
  })

  container_{{ card }}.addEventListener('mouseout', function(){
    overlay_{{ card }}.style = 'filter : opacity(0)'
    container_{{ card }}.style = 'transform : perspective(350px) rotateY(0deg) rotateX(0deg)'
  })
  {% endfor %}
</script>

{% endblock content %}

spartamarket/users/templates/users/document.html
{% extends "base.html" %}
{% load static %}

{% block style %}
  <style>
    .title_box {
      margin: 20px;
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
    .sort_box {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
    .btn_set {
      background-color: transparent;
      border-radius: 5px;
      height: 50px;
      margin-right: 50px;
    }

    .container {
      width: 220px; height: 310px; transition : all 0.1s;
      position: relative;
    }
    .overlay {
      position: absolute;
      width: 220px;
      height: 310px;
      background: linear-gradient(105deg,
      transparent 40%,
      rgba(255, 219, 112, 0.8) 45%,
      rgba(132, 50, 255 ,0.6) 50%,
      transparent 54%);
      filter: brightness(1.1) opacity(0.8);
      mix-blend-mode: color-dodge;
      background-size: 150% 150%;
      background-position: 100%;
      transition: all 0.1s;
      z-index: 1;
    }
    .card {
      width: 220px; height: 310px;
      background-size: cover;
    }
  </style>
{% endblock %}

{% block content %}
<br>
<div class="title_box">
    <h1>카드 도감</h1> 
  </div>
  <br><hr>
<br>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
  {% for card in cards %}
  <div style="display: flex; flex-direction: column; justify-content: center; margin: 10px;">
      <div style="text-align: center;" > No. {{ card }}</div>
      <div class="container" id="container_{{ card }}"> <!-- 각 container에 고유한 id 추가 -->
        <div class="overlay"></div>
        <img class="card" src="{% static 'stores/pokemon ('|add:card|add:').png' %}" >
      </div>
  </div>
  {% endfor %}
</div>
<script>
  // 각 container에 대해 이벤트 리스너 추가
  {% for card in cards %}
  var container_{{ card }} = document.querySelector('#container_{{ card }}');
  var overlay_{{ card }} = container_{{ card }}.querySelector('.overlay');

  container_{{ card }}.addEventListener('mousemove', function(e){
    var x = e.offsetX
    var y = e.offsetY
    var rotateY = -1/5 * x + 20
    var rotateX = 4/30 * y - 20

    overlay_{{ card }}.style = `background-position : ${x/5 + y/5}%; filter : opacity(${x/200}) brightness(1.2)`

    container_{{ card }}.style = `transform : perspective(350px) rotateX(${rotateX}deg) rotateY(${rotateY}deg)`
  })

  container_{{ card }}.addEventListener('mouseout', function(){
    overlay_{{ card }}.style = 'filter : opacity(0)'
    container_{{ card }}.style = 'transform : perspective(350px) rotateY(0deg) rotateX(0deg)'
  })
  {% endfor %}
</script>

{% endblock content %}

spartamarket/users/templates/users/gatcha.html
{% extends "base.html" %}
{% load static %}

{% block style %}
<style>
    .gatcha_box {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .container {
        width: 220px;
        height: 310px;
        transition: all 0.1s;
        position: relative;
    }

    .overlay {
        position: absolute;
        width: 220px;
        height: 310px;
        background: linear-gradient(105deg,
                transparent 40%,
                rgba(255, 219, 112, 0.8) 45%,
                rgba(132, 50, 255, 0.6) 50%,
                transparent 54%);
        filter: brightness(1.1) opacity(0.8);
        mix-blend-mode: color-dodge;
        background-size: 150% 150%;
        background-position: 100%;
        transition: all 0.1s;
        z-index: 1;
    }

    .card {
        width: 220px;
        height: 310px;
        background-size: cover;
    }
</style>
{% endblock style %}

{% block content %}
<br>
<div class="title_box">
    <h1>카드 뽑기</h1>
</div>
<br>
<hr>
<br>


<div class="gatcha_box">
    {% if gatcha %}
    <p class="g_box">
    <h2>축하합니다</h2>
    <p style="display: flex; flex-direction: column; justify-content: center; width: 220px; ">
        <label style="text-align: center;"> No. {{ gatcha }}</label>
        <img src="{% static 'stores/pokemon ('|add:gatcha|add:').png' %}" style="width: 200px; margin: 10px;">
    </p>
    <label> 1회당 100 포인트</label>
    <form action="{% url "users:gatcha" %}" method="POST">
        {% csrf_token %}
        <button type="submit">한번 더 뽑기</button>
    </form>
    <br>
    <label> 내 카드 확인하기</label>
    <a href="{% url "users:cards" user.pk %}"> <button>보유 카드 보기</button> </a>
    <br>
    {% else %}
    <h2>어서 오세요</h2>
    <img src="{% static 'stores/pokemon (blank).png' %}" style="width: 200px; margin: 10px;">
    <br>
    <label> 1회당 100 포인트</label>
    <form action="{% url "users:gatcha" %}" method="POST">
        {% csrf_token %}
        <button type="submit">뽑기</button>
        <br>
        {% endif %}
        </p>
</div>


{% endblock content %}

spartamarket/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <style>
    .custom_box {
      display: flex;
      justify-content: space-evenly;
      align-items: center;
    }
    .title_box {
      margin: 20px;
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
    }
  </style>
{% endblock %}

{% block content %}
<div class="title_box">
  <h1>회원프로필</h1>
  {{ member }}님의 | 팔로워 : {{ member.followers.count }} 명 | 팔로잉 : {{ member.following.count }} 명
  {% if request.user != user %}
  <form action="{% url 'users:follow' user.id %}" method="POST">
    {% csrf_token %}
    {% if request.user in member.followers.all %}
    {% comment %} 팔로우 상태 {% endcomment %}
    <button class="btn_set" >팔로우 <img src="{% static "users/add-friend.png" %}" style="width: 30px; height: 30px;"></button> 
    {% else %}
    {% comment %} 언팔로우 상태 {% endcomment %}
    <button class="btn_set" >언팔로우 <img src="{% static "users/delete-friend.png" %}" style="width: 30px; height: 30px;"></button>
    {% endif %}
  {% endif %}
  </form>
</div>
<hr /><br />
  <div class="custom_box">
    <div>
      <p>
        <h2 for="id_image"><프로필 이미지></h2>
        <img id="preview"
          style="width: 350px; height: 350px;"
          src="{% if user.image %}
            {{ user.image.url }}
          {% else %}
            {% static 'accounts/user.png' %}
          {% endif %}" />
        <br />
      </p>
    </div>
    <div>
      <p>
        <h2 class="labels" for="id_username">아이디 : {{ user.username }}</h2>
      </p>
      <br />
      <p>
        <h2 class="labels" for="id_last_name">유저이름 : {{ user.last_name }}{{ user.first_name }}</h2>
      </p>
      <br />
      <p>
        <h2 class="labels" for="id_email">이메일 : {{ user.email }}</h2>
      </p>
      <br />
      <p>
        <h2 class="labels" for="id_point">보유 포인트 : {{ user.point }}</h2>
      </p>
      <br />
    </div>
  </div>
  {% if request.user == user or request.user.is_superuser or is_staff %}
  <div style="display: flex; justify-content: end;">
    <a href="{% url 'accounts:update' %}" style="margin-right: 20px;"><button>수정하기</button></a>
    <form action="{% url 'accounts:delete' %}" method="POST" style="margin-right: 100px;">
      {% csrf_token %}
      <button type="button" onclick="removeCheck()">계정삭제</button>
    </form>
  </div>
  {% endif %}
  <br />
  <div class="title_box">
  <h2>작성 게시글</h2> 
  <a href="{% url "users:cards" user.pk %}"> <button>보유 카드 보기</button> </a>
  <a href="{% url "articles:like_articles" user.pk %}"> <button>찜 목록 보기</button> </a>
  </div>
  <hr /><br />
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for article in articles %}
      <a href="{% url 'articles:articles_view' article.pk %}  ">
        <div class="col" style="width: 326px;">
          <div class="card" style="align-items: center;">
            <img class="imgs" src="{{ article.image.url }}" class="card-img-top" />
            <div class="card-body">
              <h3 class="card-title">{{ article.title }}</h3>
              <div style="display: flex; flex-direction: row; margin-top: 10px;">
                <p class="card-text" style="margin-right: 20px;">{{ article.like_users.all|length }} 좋아요</p>
                <p class="card-text" style="margin-right: 20px;">{{ article.views }} 조회수 </p>
                  <p class="card-text">{{ article.comments.all|length }} 댓글</p>
              </div>
            </div>
          </div>
        </div>
      </a>
    {% endfor %}
  </div>
  <br />
{% endblock %}