spartamarket/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

spartamarket/articles/urls.py
from django.urls import path
from . import views



app_name = "articles"
urlpatterns = [
    path('about/', views.about, name='about'),
    path('articles/', views.articles, name='articles'),
    path('articles_view/<int:pk>/', views.articles_view, name='articles_view'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('update/<int:pk>', views.update, name='update'),
    path('like/<int:pk>/', views.like, name='like'),
    path('like/articles/<int:pk>/', views.like_articles, name='like_articles'),
    path('comment_create/<int:pk>/', views.comment_create, name='comment_create'),
    path('comment_delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('hashtag/<int:hash_pk>/', views.hashtag, name='hashtag'),
]

spartamarket/spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from articles import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('articles/', include("articles.urls")),
    path('users/', include("users.urls")),
    path('accounts/', include("accounts.urls")),
    path('stores/', include("stores.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}), # 이부분 추가!!
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spartamarket/stores/urls.py
from django.urls import path
from . import views


app_name = "stores"
urlpatterns = [
    path('stores/', views.stores, name='stores'),
    path('stores_view/<int:pk>/', views.stores_view, name='stores_view'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('update/<int:pk>', views.update, name='update'),
    path('buy/<int:pk>', views.buy, name='buy'),
]

spartamarket/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_id>', views.follow, name='follow'),
    path('gatcha/', views.gatcha, name='gatcha'),
    path('cards/<int:pk>/', views.cards, name='cards'),
    path('card_storage/<int:pk>/', views.card_storage, name='card_storage'),
    path('document/', views.document, name='document'),
]

spartamarket/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <title>SpartaMarket</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
      body{
        background-color: var(--background_color);
      }
      #wrap {
        min-height: calc(100vh - 10rem); /* footer 높이를 빼준다. */
      }
      footer {
        height: 10rem; /* footer 높이 */
      }
      .imgs {
        width: 290px;
        height: 290px;
        margin-top: 20px;
      }
      .card-title{
        width: 300px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }
      .card-body{
        padding-left: 50px;
      }
    </style>
    {% block style %}
    {% endblock style %}
  </head>
  <body>
    {% if messages %}
<div class="messages">
    {% for message in messages %}
    <script>
      alert('{{message}}');
    </script>
    {% endfor %}
</div>
{% endif %}
    <div id="wrap">
      <nav class="navbar navbar-expand-lg" style="background-color: var(--point_color);">
        <div class="container-fluid" style="margin: 0 30px;">
          <img src="{% static 'articles/market.png' %}" style="width: 30px; margin-right: 10px;"/>
          <a class="navbar-brand" aria-current="page" href="{% url 'index' %}"><strong>스파르타</strong></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url "articles:articles" %}">게시물 보기</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "articles:create" %}">게시물 작성</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "stores:stores" %}">장터 보기</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "stores:create" %}">판매글 작성</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "users:gatcha" %}">카드 뽑기</a>
              </li>
            </ul>
          </div>
          {% if request.user.is_authenticated %}
          <label> 당신의 포인트 : {{ request.user.point }} 포인트</label>
          <label class="nav-item dropdown" style="margin-right: 30px;">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{% if request.user.image %}{{ request.user.image.url }}{% else %}{% static 'articles/user.png' %}{% endif %}" style="width: 30px; margin: 0 20px;">
            </a>
            <ul class="dropdown-menu">
              <form action="{% url "users:profile" request.user.username %}" method="GET">
                  <li class="nav-item" style="margin-left: 30px;">
                    <input class="nav-link" type="submit" value="내 프로필">
                  </li>
              </form>
              <li><hr class="dropdown-divider"></li>
              <form action="{% url "accounts:logout" %}" method="POST">
                {% csrf_token %}
                  <li class="nav-item" style="margin-left: 30px;">
                    <input class="nav-link" type="submit" value="로그아웃">
                  </li>
                </form>
            </ul>
          </label>
          {% else %}
          <label class="nav-item" style="margin-right: 30px;">
            <a class="nav-link" href="{% url "accounts:login" %}">로그인</a>
          </label>
          {% endif %}
          <div>
            <form class="d-flex" role="search" action="{% url "articles:articles" %}" method="GET">
              <select class="form-select" aria-label="Default select example" name="select" style="width: 100px;">
                <option selected value="title">제목</option>
                <option value="content">내용</option>
                <option value="author">작성자</option>
              </select>
              <input class="form-control me-2" type="search" placeholder="입력" aria-label="Search" name="search" />
              <button class="btn btn-outline-success" type="submit" style="white-space: nowrap;">검색</button>
            </form>
          </div>
        </div>
      </nav>
      {% block main %}

      {% endblock main %}
      <div style="margin: 0 200px;">
        {% block content %}
        
        {% endblock %}
      </div>
    </div>
    <footer class="py-3" style="background-color: var(--point_color);">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item">
          <a href="{% url "index" %}" class="nav-link px-2 text-muted">메인화면</a>
        </li>
        <li class="nav-item">
          <a href="{% url "users:document" %}" class="nav-link px-2 text-muted">카드도감</a>
        </li>
        <li class="nav-item">
          <a href="{% url "articles:about" %}" class="nav-link px-2 text-muted">설명</a>
        </li>
      </ul>
      <p class="text-center text-muted">© 2024 Sparta.Inc</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>